### ISSUE TITLE
Add option for in-game blocks to "muffle"

### ISSUE THREAD

**Issue by yesido9** [Skoice/skoice#22]
This could be an interesting feature to make proximity chat even more dynamic. Not sure if this is possible, but a way for blocks to reduce the range of proximity chat for players behind solid walls and ceilings would be interesting. One example of how it'd work is that a group of players inside a house would have their own channel while players outside would be put in a different one even if they are technically within range.
There could be an option in the voice.yml to enable or disable this behavior. There could maybe even be more advanced options, such as excluding certain types of blocks from this behavior like non-opaque blocks.

**Comment by busterbeam** [comment]
Noticed this has not been answered. Not an expert myself either, but having audio "travel" through environment is not simple addition.  It's pretty much ray tracing all over again, and who does the compute?  server or client?

**Comment by LucasCdry** [comment]
Hey! Thank you for your suggestion. As someone said above, such a feature would be extremely difficult to implement and would require a lot of processing power. With that being said, we do not plan on implementing that feature in the near future.
