### ISSUE TITLE
Music bots (suggestion)

### ISSUE THREAD

**Issue by Zeelia** [Skoice/skoice#26]
It would be nice to be able to link a music bot which is on the Discord server, to a Minecraft player, effectively making the bot jump around together with the player in the proximity voice chats. 

For instance, I would link the music bot Tempo to my Minecraft player. Then, I join the Skoice proximity voice chat, and I also make Tempo join. Now, since Tempo is linked to my Minecraft player, it would receive the same coordinates as me, making Tempo always be in the same proximity voice chat together with me.

**Comment by LucasCdry** [comment]
Hey! Thank you for your suggestion. This feature is very specific and is not likely to be implemented in the near future. Moreover, with a music bot, people cannot use Skoice the "sneaky way" which can be an issue for some players.
