### ISSUE TITLE
Add Velocity Proxy Support

### ISSUE THREAD

**Issue by flashbtw** [Skoice/skoice#27]
A rather nice feature to be implemented would be MySQL / MariaDB support. The simple reason for this is my wish to connect multiple Minecraft servers with only one discord server because I got a waterfall-proxied server network. 
This can be considered an enhancement that can be necessary for many networks searching for a solution implementing proximity chat on their servers.

**Comment by carlodrift** [comment]
Hi there! We've implemented Velocity proxy support for the upcoming update. Bungeecord/Waterfall are getting old, so we may not add support for them.
This means that it will now be possible to use the same Skoice proximity voice chat on several separate servers.
We'll be releasing this in our beta update channel soon.
