### ISSUE TITLE
Use link of EssentialX Discord Link

### ISSUE THREAD

**Issue by GeoffreyParrier** [Skoice/skoice#44]
It could be interesting to use the link of EssentialX Discord Link to link only one time accounts of players if this plugin and Discord Link are in use.

Here's the documentation for Discord Link :
https://essentialsx.net/wiki/Discord-Link.html

**Comment by PetyXbron** [comment]
I'm in! Great idea, this would be really cooool. 🚀

**Comment by carlodrift** [comment]
We have submitted this pull request to EssentialsX, which adds an additional method to their API: https://github.com/EssentialsX/Essentials/pull/5896
This is not required for the implementation of the feature, but it would make it simpler.
We are awaiting their feedback

**Comment by carlodrift** [comment]
Ready for the next update this summer. Thanks for the suggestion.

**Comment by PetyXbron** [comment]
@carlodrift cool, just let us know then! 😁

**Comment by carlodrift** [comment]
It's available in the latest version. It was introduced in Skoice 3.2 in September 🙂
Changelog: https://www.spigotmc.org/resources/skoice-proximity-voice-chat.82861/update?update=561322
