### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by Viahduc** [Skoice/skoice#45]
Hello, i have installed Skoice 3.0.9 on my 1.8.8 minecraft server running spigot. I have already installed a plugin named taupegun and managed to make it work. Skoice.jar is in the plugins file. However, when I launch the server, Skoice doesn't get loaded when it is alone or with the taupegun plugin. There is no message telling me there was an error. Am I doing something wrong or is it just a problem with the new update?

**Comment by carlodrift** [comment]
We can help you on our Discord server: https://discord.gg/h3Tgccc
