### ISSUE TITLE
Entire channels of players being moved when getting in proximity

### ISSUE THREAD

**Issue by Yovez** [Skoice/skoice#46]
Hi there, It's kind of hard to explain but we have around 20 people in voice chat using the plugin and what not. When moving around sometimes when ur in a group of like 5 sometimes when a new player walks in proximity it, if the player was in a proximity group already it will move that entire group of players to the channel, and then slowly move them out after. It can be quite weird and sometimes annoying

**Comment by LucasCdry** [comment]
Hey! We are aware of this issue (#21) and have come up with a solution that we will eventually implement in a future version.
